"""ste nullable true for link and icon in module and sub_module table

Revision ID: 1757efcee769
Revises: 94c1adcd4038
Create Date: 2023-09-07 19:30:28.763280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1757efcee769'
down_revision: Union[str, None] = '94c1adcd4038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('module', 'link',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('module', 'icon_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('sub_module', 'link',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('sub_module', 'icon_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('usertype_modules_map', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('usertype_sub_modules_map', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usertype_sub_modules_map', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('usertype_modules_map', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sub_module', 'icon_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('sub_module', 'link',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('module', 'icon_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('module', 'link',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
