"""add models for define user type based modules and sub modules

Revision ID: 23bc00a5e047
Revises: 1278fd4a22c2
Create Date: 2023-09-06 10:37:25.793978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23bc00a5e047'
down_revision: Union[str, None] = '1278fd4a22c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usertype_modules_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usertype_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.ForeignKeyConstraint(['usertype_id'], ['usertype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usertype_sub_modules_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usertype_id', sa.Integer(), nullable=True),
    sa.Column('sub_module_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sub_module_id'], ['sub_module.id'], ),
    sa.ForeignKeyConstraint(['usertype_id'], ['usertype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('user', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'is_executive',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_executive',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_table('usertype_sub_modules_map')
    op.drop_table('usertype_modules_map')
    op.drop_table('sub_module')
    op.drop_table('module')
    # ### end Alembic commands ###
