"""add link and icon in module and sub_module table

Revision ID: 2d5627e92b62
Revises: 23bc00a5e047
Create Date: 2023-09-07 19:20:32.663710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d5627e92b62'
down_revision: Union[str, None] = '23bc00a5e047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module', sa.Column('link', sa.String(length=200), nullable=True))
    op.add_column('module', sa.Column('icon_name', sa.String(length=150), nullable=True))
    op.add_column('sub_module', sa.Column('link', sa.String(length=200), nullable=True))
    op.add_column('sub_module', sa.Column('icon_name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_module', 'icon_name')
    op.drop_column('sub_module', 'link')
    op.drop_column('module', 'icon_name')
    op.drop_column('module', 'link')
    # ### end Alembic commands ###
