"""add token

Revision ID: 6b660d8bf7ab
Revises: 1757efcee769
Create Date: 2023-09-08 19:05:24.484818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b660d8bf7ab'
down_revision: Union[str, None] = '1757efcee769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_usertype_map', sa.Column('token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_usertype_map', 'token')
    # ### end Alembic commands ###
