"""ste nullable for link and icon in module and sub_module table

Revision ID: 94c1adcd4038
Revises: 2d5627e92b62
Create Date: 2023-09-07 19:22:55.891720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c1adcd4038'
down_revision: Union[str, None] = '2d5627e92b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('module', 'link',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('module', 'icon_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('sub_module', 'link',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('sub_module', 'icon_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sub_module', 'icon_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('sub_module', 'link',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('module', 'icon_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('module', 'link',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
